package com.diaa.theholyquran;

import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;
import androidx.viewpager.widget.ViewPager;

public class MainActivity extends AppCompatActivity {
    private String[] imageUrls = new String[]{
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/604.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/603.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/602.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/601.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/600.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/599.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/598.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/597.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/596.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/595.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/594.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/593.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/592.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/591.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/590.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/589.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/588.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/587.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/586.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/585.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/584.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/583.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/582.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/581.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/580.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/579.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/578.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/577.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/576.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/575.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/574.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/573.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/572.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/571.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/570.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/569.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/568.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/567.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/566.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/565.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/564.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/563.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/562.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/561.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/560.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/559.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/558.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/557.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/556.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/555.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/554.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/553.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/552.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/551.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/550.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/549.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/548.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/547.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/546.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/545.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/544.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/543.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/542.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/541.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/540.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/539.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/538.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/537.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/536.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/535.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/534.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/533.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/532.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/531.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/530.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/529.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/528.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/527.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/526.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/525.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/524.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/523.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/522.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/521.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/520.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/519.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/518.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/517.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/516.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/515.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/514.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/513.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/512.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/511.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/510.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/509.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/508.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/507.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/506.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/505.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/504.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/503.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/502.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/501.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/500.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/499.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/498.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/497.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/496.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/495.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/494.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/493.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/492.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/491.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/490.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/489.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/488.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/487.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/486.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/485.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/484.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/483.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/482.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/481.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/480.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/479.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/478.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/477.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/476.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/475.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/474.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/473.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/472.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/471.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/470.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/469.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/468.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/467.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/466.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/465.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/464.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/463.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/462.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/461.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/460.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/459.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/458.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/457.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/456.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/455.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/454.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/453.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/452.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/451.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/450.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/449.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/448.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/447.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/446.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/445.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/444.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/443.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/442.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/441.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/440.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/439.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/438.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/437.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/436.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/435.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/434.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/433.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/432.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/431.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/430.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/429.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/428.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/427.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/426.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/425.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/424.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/423.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/422.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/421.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/420.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/419.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/418.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/417.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/416.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/415.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/414.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/413.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/412.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/411.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/410.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/409.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/408.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/407.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/406.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/405.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/404.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/403.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/402.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/401.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/400.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/399.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/398.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/397.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/396.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/395.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/394.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/393.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/392.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/391.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/390.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/389.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/388.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/387.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/386.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/385.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/384.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/383.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/382.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/381.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/380.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/379.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/378.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/377.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/376.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/375.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/374.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/373.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/372.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/371.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/370.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/369.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/368.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/367.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/366.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/365.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/364.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/363.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/362.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/361.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/360.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/359.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/358.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/357.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/356.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/355.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/354.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/353.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/352.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/351.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/350.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/349.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/348.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/347.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/346.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/345.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/344.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/343.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/342.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/341.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/340.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/339.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/338.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/337.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/336.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/335.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/334.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/333.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/332.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/331.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/330.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/329.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/328.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/327.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/326.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/325.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/324.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/323.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/322.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/321.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/320.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/319.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/318.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/317.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/316.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/315.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/314.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/313.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/312.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/311.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/310.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/309.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/308.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/307.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/306.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/305.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/304.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/303.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/302.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/301.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/300.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/299.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/298.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/297.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/296.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/295.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/294.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/293.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/292.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/291.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/290.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/289.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/288.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/287.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/286.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/285.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/284.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/283.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/282.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/281.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/280.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/279.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/278.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/277.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/276.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/275.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/274.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/273.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/272.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/271.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/270.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/269.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/268.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/267.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/266.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/265.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/264.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/263.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/262.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/261.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/260.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/259.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/258.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/257.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/256.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/255.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/254.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/253.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/252.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/251.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/250.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/249.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/248.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/247.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/246.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/245.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/244.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/243.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/242.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/241.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/240.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/239.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/238.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/237.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/236.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/235.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/234.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/233.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/232.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/231.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/230.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/229.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/228.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/227.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/226.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/225.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/224.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/223.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/222.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/221.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/220.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/219.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/218.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/217.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/216.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/215.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/214.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/213.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/212.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/211.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/210.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/209.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/208.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/207.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/206.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/205.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/204.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/203.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/202.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/201.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/200.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/199.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/198.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/197.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/196.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/195.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/194.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/193.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/192.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/191.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/190.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/189.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/188.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/187.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/186.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/185.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/184.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/183.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/182.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/181.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/180.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/179.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/178.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/177.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/176.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/175.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/174.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/173.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/172.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/171.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/170.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/169.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/168.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/167.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/166.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/165.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/164.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/163.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/162.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/161.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/160.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/159.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/158.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/157.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/156.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/155.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/154.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/153.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/152.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/151.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/150.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/149.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/148.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/147.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/146.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/145.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/144.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/143.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/142.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/141.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/140.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/139.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/138.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/137.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/136.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/135.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/134.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/133.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/132.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/131.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/130.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/129.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/128.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/127.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/126.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/125.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/124.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/123.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/122.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/121.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/120.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/119.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/118.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/117.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/116.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/115.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/114.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/113.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/112.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/111.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/110.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/109.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/108.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/107.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/106.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/105.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/104.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/103.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/102.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/101.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/100.png",
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/99.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/98.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/97.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/96.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/95.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/94.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/93.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/92.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/91.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/90.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/89.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/88.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/87.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/86.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/85.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/84.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/83.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/82.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/81.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/80.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/79.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/78.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/77.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/76.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/75.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/74.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/73.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/72.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/71.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/70.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/69.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/68.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/67.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/66.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/65.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/64.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/63.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/62.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/61.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/60.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/59.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/58.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/57.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/56.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/55.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/54.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/53.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/52.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/51.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/50.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/49.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/48.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/47.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/46.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/45.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/44.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/43.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/42.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/41.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/40.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/39.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/38.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/37.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/36.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/35.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/34.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/33.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/32.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/31.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/30.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/29.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/28.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/27.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/26.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/25.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/24.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/23.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/22.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/21.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/20.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/19.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/18.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/17.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/16.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/15.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/14.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/13.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/12.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/11.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/10.png" ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/9.png"  ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/8.png"  ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/7.png"  ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/6.png"  ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/5.png"  ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/4.png"  ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/3.png"  ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/2.png"  ,
            "https://raw.githubusercontent.com/diaaaaaa/TheHolyQuran/master/app/src/main/assets/1.png"
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ViewPager viewPager = findViewById(R.id.view_pager);
        ViewPagerAdapter adapter = new ViewPagerAdapter(this, imageUrls);
        viewPager.setAdapter(adapter);
    }
}


